name: Workflow Chain Example

on:
  workflow_dispatch:

jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:   
    - name: Echo job name
      run: "echo Job ${{ github.job }}"

  job_2:
    runs-on: ubuntu-latest
    needs: job_1 
    steps:   
    - name: Echo job name
      run: "echo Job ${{ github.job }}"

  job_3: 
    runs-on: ubuntu-latest   
    needs: job_1
    steps:   
    - name: Echo job name
      run: "echo Job ${{ github.job }}"

  job_4: 
    runs-on: ubuntu-latest   
    needs: [job_2,job_3]
    steps:   
    - name: Echo job name
      run: "echo Job ${{ github.job }}"
